name: Build

on:
  push:
    branches: [ "build-workflow-1" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      BUILD_CONFIGURATION: 'Release'
      VERSION: '1.0.${{github.run_number}}'

    steps:
    - uses: actions/checkout@v3
        
    - name: Print Build Number
      run: echo "Build number is $VERSION"
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore Dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration $BUILD_CONFIGURATION
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Nuget Pack
      run: dotnet pack --no-build -p:Version=$VERSION --configuration $BUILD_CONFIGURATION --output "${{github.workspace}}/package/" "./Lib/PixelByProxy.Asus.Router.csproj"
    
    - name: Create Artifact
      uses: actions/upload-artifact@v2
      with:
        name: PixelbyProxy.Asus.Router.${{env.VERSION}}-preview
        path: "${{github.workspace}}/package/"