name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      BUILD_CONFIGURATION: 'Release'
      VERSION: '1.0'

    steps:
    - uses: actions/checkout@v3
    
    - name: Generate Build Number
      id: ${{env.VERSION}}
      uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.github_token}}
        
    - name: Print Build Number
      run: echo "Build number is $BUILD_NUMBER"
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore Dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Nuget Pack
      run: dotnet pack --no-build -p:Version=$BUILD_NUMBER --configuration ${{env.BUILD_CONFIGURATION}} --output "${{github.workspace}}/package/" "./Lib/PixelByProxy.Asus.Router.csproj"
