name: Build Nuget

on:
  push:
    branches:
      - main
      
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      BUILD_CONFIGURATION: 'Release'
      VERSION: '1.0.${{github.run_number}}'

    steps:
    - uses: actions/checkout@v3
        
    - name: Print Build Number
      run: echo "Build number is $VERSION"
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore Dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration $BUILD_CONFIGURATION
      
    - name: Nuget Pack
      run: dotnet pack --no-build -p:Version=$VERSION --configuration $BUILD_CONFIGURATION --output "${{github.workspace}}/package/" "./src/Lib/PixelByProxy.Asus.Router.csproj"
    
    - name: Create Artifact
      uses: actions/upload-artifact@v2
      with:
        name: NugetPreRelease
        path: "${{github.workspace}}/package/"
