name: Release Nuget

on:
  workflow_dispatch:

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Download Artifact
        uses: bettermarks/action-artifact-download@0.3.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          artifact_name: NugetPreRelease
          rename: nuget.zip

      - name: Extract Nuget
        uses: montudor/action-zip@v1
        with:
          args: unzip -qq nuget.zip -d packages

      - name: Display Files
        run: ls -R

      - name: Nuget.org Push Packages
        run: nuget push "packages/*.nupkg" -ApiKey ${{secrets.NUGET_KEY}} -Source "https://api.nuget.org/v3/index.json" -SkipDuplicate

      - name: Github Push Packages
        run: nuget push "packages/*.nupkg" -ApiKey ${{secrets.GITHUB_TOKEN}} -Source "github" -SkipDuplicate
