name: Release Nuget

on:
  workflow_dispatch:

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Download Artifact
        uses: bettermarks/action-artifact-download@0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: NugetPreRelease
          rename: nuget.zip

      - name: Display Files 1
        run: ls -R

      - name: Extract Nuget
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r nuget.zip packages

      - name: Dir
        run: cd packages

      - name: Display Files
        run: ls -R