name: Validate Pull Request

on:
  pull_request:
    branches:    
      - main
      
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      BUILD_CONFIGURATION: 'Release'

    steps:
    - uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore Dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration $BUILD_CONFIGURATION
